export enum ProfileRoutesEnum {
  PROFILE = "profile",
  STUDENT = "student",
  TEACHER = "teacher",
  CLASS = "class",
  SUBJECT = "subject",
  TOPIC = "topic",
  SAMPLE_PAPER = "sample-paper",
  VIEW_SAMPLE_PAPER = "view-sample-paper",
  SYLLABUS = "syllabus",
  SETTINGS = "settings",
  PRIVACY_POLICY = "privacy-policy",
  CONFERENCING = "conference",
  VIDEO = "video",
  NOTES = "notes",
}
